export const LOGGEDIN_VALIDATE_USER_REQUEST = "LOGGEDIN_VALIDATE_USER_REQUEST";
export const LOGGEDIN_VALIDATE_USER_SUCCESS = "LOGGEDIN_VALIDATE_USER_SUCCESS";
export const LOGGEDIN_VALIDATE_USER_FAILURE = "LOGGEDIN_VALIDATE_USER_FAILURE";