export const USER_LICENCE_ID = "USER_LICENCE_ID";
export const IS_USER_LICENCE_ID_ERROR = "IS_USER_LICENCE_ID_ERROR";
export const USER_EMAIL_ADDRESS = "USER_EMAIL_ADDRESS";
export const IS_USER_EMAIL_ADDRESS_ERROR = "IS_USER_EMAIL_ADDRESS_ERROR";
export const USER_PASSWORD = "USER_PASSWORD";
export const IS_USER_PASSWORD_ERROR = "IS_USER_PASSWORD_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
